name: artwork_extractor_dart
description: A simple library to extract & save artwork of a music/audio file.
version: 1.0.0
homepage: https://github.com/mytja/artwork_extractor_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  ffi: ^1.1.2

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
