name: artwork_extractor_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: 

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
